# Generated by Django 3.1.7 on 2021-03-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'permissions': {('is_admin', 'is admin'), ('is_empleado', 'is empleado')}},
        ),
    ]
